### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by itcreator** [clue/php-redis-react#32]
When I use Clue\React\Redis\Factory

``` php
$factory = new Factory($loop);
$factory->createClient('redis_docker_aliase')
->then(....
...
```

I see error

```
exception 'React\SocketClient\ConnectionException' with message 'Connection refused' in /code/vendor/react/socket-client/React/SocketClient/Connector.php:76
Stack trace:
#0 [internal function]: React\SocketClient\Connector->checkConnectedSocket(Resource id #185)
#1 /code/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, Resource id #185)
#2 /code/vendor/react/promise/src/React/Promise/Deferred.php(39): React\Promise\FulfilledPromise->then(Array, NULL)
#3 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#4 /code/vendor/react/promise/src/React/Promise/Deferred.php(102): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#5 /code/vendor/react/promise/src/React/Promise/Deferred.php(60): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#6 /code/vendor/react/socket-client/React/SocketClient/Connector.php(65): React\Promise\Deferred->resolve(Resource id #185)
#7 [internal function]: React\SocketClient\Connector->React\SocketClient\{closure}(Resource id #185, Object(React\EventLoop\StreamSelectLoop))
#8 /code/vendor/react/event-loop/React/EventLoop/StreamSelectLoop.php(160): call_user_func(Object(Closure), Resource id #185, Object(React\EventLoop\StreamSelectLoop))
#9 /code/vendor/react/event-loop/React/EventLoop/StreamSelectLoop.php(169): React\EventLoop\StreamSelectLoop->runStreamSelect(true)
#10 /code/vendor/react/event-loop/React/EventLoop/StreamSelectLoop.php(182): React\EventLoop\StreamSelectLoop->loop()
```

**Comment by fesor** [comment]
I think that this is `react/dns` issue.

**Comment by clue** [comment]
Thanks for spotting and reporting!

This actually depends on an upstream component (react/socket-client) and there's little we can do about this here. I've filed a relevant ticket here: https://github.com/reactphp/socket-client/issues/35

**Comment by clue** [comment]
Small progress update: This has been fixed via https://github.com/reactphp/dns/pull/75 and https://github.com/reactphp/socket/pull/112 last month. So if you update your dependencies, this should now work out of the box :+1: 

However, I've marked this for the `v2.1.0` milestone, as reliably requiring this feature here requires the switch to the Socket component first, which is a BC break targeted for the `v2.0.0` release (see #50).
